<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'UserRbac\Module'                                    => __DIR__ . '/Module.php',
  'UserRbac\Entity\UserRoleLinker'                     => __DIR__ . '/src/UserRbac/Entity/UserRoleLinker.php',
  'UserRbac\Entity\UserRoleLinkerInterface'            => __DIR__ . '/src/UserRbac/Entity/UserRoleLinkerInterface.php',
  'UserRbac\Factory\IdentityProviderFactory'           => __DIR__ . '/src/UserRbac/Factory/IdentityProviderFactory.php',
  'UserRbac\Factory\IdentityRoleProviderFactory'       => __DIR__ . '/src/UserRbac/Factory/IdentityRoleProviderFactory.php',
  'UserRbac\Factory\ModuleOptionsFactory'              => __DIR__ . '/src/UserRbac/Factory/ModuleOptionsFactory.php',
  'UserRbac\Factory\SmartRedirectStrategyFactory'      => __DIR__ . '/src/UserRbac/Factory/SmartRedirectStrategyFactory.php',
  'UserRbac\Factory\UserRoleLinkerMapperFactory'       => __DIR__ . '/src/UserRbac/Factory/UserRoleLinkerMapperFactory.php',
  'UserRbac\Identity\IdentityProvider'                 => __DIR__ . '/src/UserRbac/Identity/IdentityProvider.php',
  'UserRbac\Identity\IdentityRoleProvider'             => __DIR__ . '/src/UserRbac/Identity/IdentityRoleProvider.php',
  'UserRbac\Mapper\Exception\InvalidArgumentException' => __DIR__ . '/src/UserRbac/Mapper/Exception/InvalidArgumentException.php',
  'UserRbac\Mapper\UserRoleLinkerMapper'               => __DIR__ . '/src/UserRbac/Mapper/UserRoleLinkerMapper.php',
  'UserRbac\Mapper\UserRoleLinkerMapperInterface'      => __DIR__ . '/src/UserRbac/Mapper/UserRoleLinkerMapperInterface.php',
  'UserRbac\Options\ModuleOptions'                     => __DIR__ . '/src/UserRbac/Options/ModuleOptions.php',
  'UserRbac\Options\ModuleOptionsInterface'            => __DIR__ . '/src/UserRbac/Options/ModuleOptionsInterface.php',
  'UserRbac\View\Strategy\SmartRedirectStrategy'       => __DIR__ . '/src/UserRbac/View/Strategy/SmartRedirectStrategy.php'
);
